name: Publish Package
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version number to increment
        required: true
        options:
          - patch
          - minor
          - major

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Need history for changelog generation
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          registry-url: https://npm.pkg.github.com/

      - run: npm ci
      - run: npm run lint:check && npm run format:check
      - run: npm run build
        if: ${{ always() }}
      - run: npm run test
        if: ${{ always() }}

      - run: |
          git config --global user.name ${{ secrets.ACTION_GITHUB_USERNAME }};
          git config --global user.email ${{ secrets.ACTION_GITHUB_EMAIL }};
      - run: npm run release -- ${{ github.event.inputs.version }} --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
